apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-whisper
spec:
  serveConfigV2: |
    applications:
      - name: whisper
        import_path: serve_app.main:whisper_ray
        runtime_env:
          working_dir: "https://github.com/Banner-Wang/whisepr-kuberay/archive/refs/heads/main.zip"
          pip: 
            - faster-whisper==1.0.3
            - typer==0.12.3
            - typing_extensions==4.12.2
            - fastapi==0.111.0
            - fastapi-cli==0.0.4
          envVars:
            MODEL_NAME: base
            MODEL_DEVICE: cpu
            MODEL_CPU_THREADS: "4"
      deployments:
        - name: FastAPIWrapper
          num_replicas: 1
          ray_actor_options:
            num_cpus: 1
  rayClusterConfig:
    rayVersion: '2.31.0' # should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.31.0
              resources:
                limits:
                  cpu: 2
                  memory: 4Gi
                requests:
                  cpu: 1
                  memory: 4Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        # logical group name, for this called small-group, also can be functional
        groupName: worker
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: rayproject/ray:2.31.0
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
                resources:
                  limits:
                    cpu: 2
                    memory: 4Gi
                  requests:
                    cpu: 1
                    memory: 4Gi